services:
  web:
    build: .
    image: asifshaukat50/hello-world:1.0
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - 8000:8000
    volumes:
      - .:/app